permalink: /:title

gems:
  - jekyll-sitemap

safe: true
lsi: false

name: SEN Symposium
title: SEN Symposium

production_url: http://www.sen-symposium.nl

exclude: ["README.md"]

blogname: SEN Symposium Blog 
description: SEN Symposium Blog.
url: http://www.sen-symposium.nl
